// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteBook.Models;

namespace NoteBook.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240603183211_migration3")]
    partial class migration3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("NoteBook.Models.TblGiris", b =>
                {
                    b.Property<int>("GirisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GirisID");

                    b.ToTable("TblGirises");
                });

            modelBuilder.Entity("NoteBook.Models.TblNotlar", b =>
                {
                    b.Property<int>("NotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NotText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotID");

                    b.ToTable("tblNotlars");
                });

            modelBuilder.Entity("NoteBook.Models.TblSifreler", b =>
                {
                    b.Property<int>("SifreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("SifreText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifreTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SifreId");

                    b.ToTable("tblSifrelers");
                });
#pragma warning restore 612, 618
        }
    }
}
